window.EPISODES=[
{n:1,ko:'태초에 신은 없었다 — 카오스에서 시작된 그리스 세계',en:'Before the Gods — The Greek World Begins with Chaos',descKo:'제우스보다 오래된 세계. 카오스, 가이아, 타르타로스와 에로스에서 우주의 첫 장면을 시작한다.',descEn:'A world older than Zeus: Chaos, Gaia, Tartarus and Eros open the first scene of the Greek cosmos.'},
{n:2,ko:'대지가 하늘을 낳고, 아들이 하늘을 쓰러뜨렸다',en:'Earth Bore the Sky, and the Son Overthrew Him',descKo:'가이아와 우라노스, 티탄의 탄생, 크로노스의 반란과 신권 교체의 시작.',descEn:'Gaia and Uranus, the birth of the Titans, and Cronus’ revolt begin the cycle of divine succession.'},
{n:3,ko:'자식을 삼키는 왕 — 크로노스의 황금시대와 제우스의 생존',en:'The King Who Swallowed His Children — Cronus and the Survival of Zeus',descKo:'예언을 두려워한 크로노스와, 돌 하나로 시작된 제우스의 생존과 반격.',descEn:'Cronus fears a prophecy, while a wrapped stone allows Zeus to survive and prepare his return.'},
{n:4,ko:'신들의 10년 전쟁 — 티타노마키아',en:'The Ten-Year War of the Gods — Titanomachy',descKo:'티탄과 올림포스 세대가 우주의 지배권을 놓고 충돌하고, 세계의 질서가 다시 나뉜다.',descEn:'Titans and the Olympian generation fight for cosmic rule, and the world is divided anew.'},
{n:5,ko:'제우스가 거의 모든 것을 잃을 뻔한 날 — 튀폰',en:'The Day Zeus Nearly Lost Everything — Typhon',descKo:'제우스의 마지막 거대한 적과, 폭풍신 대 뱀 괴물이라는 고대 서아시아의 반복 모티프.',descEn:'Zeus faces his last great challenger and the ancient West Asian motif of storm god versus serpent.'},
{n:6,ko:'인간은 누가 만들었는가 — 프로메테우스와 불',en:'Who Made Humans? — Prometheus and Fire',descKo:'메코네의 제물 분배, 불의 절도, 그리고 인간 창조를 둘러싼 서로 다른 전승.',descEn:'The division of sacrifice at Mecone, the theft of fire, and competing traditions about human origins.'},
{n:7,ko:'판도라의 항아리 — 마지막에 남은 것은 정말 희망이었을까',en:'Pandora’s Jar — Was What Remained Really Hope?',descKo:'상자가 아니라 항아리였던 판도라 전승과, 엘피스의 의미를 둘러싼 오래된 논쟁.',descEn:'Pandora had a jar, not a box, and the meaning of the remaining elpis is far from simple.'},
{n:8,ko:'세상을 삼킨 물 — 아트라하시스, 노아, 데우칼리온',en:'The Waters That Swallowed the World — Atrahasis, Noah, and Deucalion',descKo:'메소포타미아·성경·그리스 홍수 전승을 문헌 연대와 고고학까지 함께 비교한다.',descEn:'Mesopotamian, Biblical, and Greek flood traditions compared through texts, chronology, and archaeology.'},
{n:9,ko:'눈을 마주치면 돌이 되는 여자 — 메두사와 페르세우스',en:'The Woman Whose Gaze Turned Men to Stone — Medusa and Perseus',descKo:'메두사는 처음부터 저주받은 인간 여성이었을까? 가장 오래된 원전부터 오비디우스까지 추적한다.',descEn:'Was Medusa always a cursed mortal woman? The tradition is traced from early Greek sources to Ovid.'},
{n:10,ko:'신보다 강했지만 자기 자신에게는 패배한 남자 — 헤라클레스',en:'Stronger Than Monsters, Defeated by Himself — Heracles',descKo:'12과업의 기원, 괴물들의 계보, 속죄와 신격화까지 헤라클레스의 모순된 생애.',descEn:'The origins of the Twelve Labors, the monster genealogy, atonement, and Heracles’ paradoxical apotheosis.'},
{n:11,ko:'페가수스를 탄 남자는 왜 하늘에서 떨어졌을까',en:'Why Did the Rider of Pegasus Fall from the Sky?',descKo:'벨레로폰과 키마이라, 동방화 시대의 괴물 이미지, 그리고 인간과 신 사이의 경계.',descEn:'Bellerophon, the Chimera, Orientalizing imagery, and the boundary between mortals and gods.'}
];